- 6.7/centos.php
See discussion on
http://community.nethserver.org/t/change-of-nethserver-upgrade-policy-proposal/2344?u=davidep
> centos.php: send major version number.

- nethserver.php
$nsrelease can be used to select a specific NethServer version
> Support $nsrelease yum var (overrides $release)

- mirrors
Monitoring mirror stability on http://www.nethserver.org/mirmon/
> Add mirrors from mrmarkuz and PCXLan.es

- mirrors
Thanks to Krajczar_Jeno
See:
- https://community.nethserver.org/t/how-to-create-your-own-nethserver-mirror/344/53?u=giacomo
- https://community.nethserver.org/t/how-to-create-your-own-nethserver-mirror/344/55?u=giacomo
> Add new hungarian mirrors

- nethserver.php
Once all mirrors are synchronized we can merge this
> Serve 7.5.1804 from mirrors

- ce-mirrors
- nethserver.php
> Support CentOS mirrors

- nethserver.php
> Archived CentOS releases from vault.centos.org

- nethserver.php
> Return full version number in mirror URL

- mirrors
Replace nethserver.globalcortex.net with mrmarkuz.dynu.net
> Replace mirror

- mirrors
Add 3 mirrors from Brazil
1 in São Paulo - Brazil (1 em São Paulo - Brasil)
2 in Minas Gerais - Brazil (2 em Minas Gerais - Brasil)
> Add mirrors from Brazil

- ce-mirrors
The current mirror is up but does not receive updates
> New chinese mirrors

- mirrors
See https://community.nethserver.org/t/how-to-create-your-own-nethserver-mirror/344/77?u=davidep
> Added mirror nethserver.interlin.nl/nethserver

- mirrors
The machine will be dismissed soon.
> Remove mirror2.nethserver.org

- ce-mirrors
Started monitoring of new mirrors here:
http://mirror-status.nethserver.org/centos.html
> Replace stale CentOS mirrors

- config.php
Merge after nethserver-subscription has been released to 7.6/updates
> Release 7.7.1908

- nethserver.php
https://github.com/NethServer/dev/issues/5867
> Serve ns6upgrade repo from mirrors

- mirrors
hosted on scaleway (fr), NethServer 7.7 on aarch64
> Add mirror armirror.framassa.org

- config.php
https://github.com/NethServer/dev/issues/6144
> Serve NS 7.7.1908 from vault repositories

- config.php
https://github.com/NethServer/dev/issues/6144
> Release of NS 7.8.2003 final

- mirrors
I tried to contact the mirror maintainer 7 days ago but got no reply.
> Remove mirror ns-mirror2.ibi.net.br

- config.php
> Serve 6.10 from vault

- .github/workflows/php.yml
- centos.php
- config.php
- nethserver.php
Allow to remove 6.10 from the "stable_releases" array
> Fix cron.php error

- mirrors
Thanks to **bradjtrammell**
https://community.nethserver.org/t/yum-update-fails-with-error-cockpit-unreachable-externally/18895/19
> Add  repos.sparkrack.com mirror

- mirrors
Thanks **to andiweidl**
See https://community.nethserver.org/t/how-to-create-your-own-nethserver-mirror/344/105
> Add neth-mirror?.email4u.co.at

- mirrors
Thanks to Krajczár Jenő we got another mirror: xindi.hu
> Add mirror xindi.hu

- mirrors
The machine will be dismissed soon
> mirrors: remove mirror1.nethserver.org
